# SERVIDOR
server:
  servlet:
    context-path: /projeto-backend
  port: 8080

spring:
  application:
    name: projeto-base
  jmx:
    enabled: false

  #CONFIGURACAO DO BANCO POSTGRES
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/projeto
    username: postgres
    password: 415782

  #ATIVANDO MIGRACAO DO FLYWAY
  flyway:
    enabled: true
    baseline-on-migrate: true

  #NAO ACEITAR ATRIBUTOS DESCONHECIDOS PELA API
  jackson:
    deserialization:
      fail-on-unknown-properties: false
    serialization:
      fail-on-empty-beans: false

#CONFIGURA??ES DE SERVIDOR DE EMAIL
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=com1.com3@gmail.com
#spring.mail.password=415782@Davi
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true



