CREATE TABLE TB001_CONTATO(
    CO_CONTATO SERIAL PRIMARY KEY,
    CO_CPF VARCHAR(11) NOT NULL,
    NO_NOME VARCHAR(100) NOT NULL,
    NU_TELEFONE_MOVEL VARCHAR(11),
    NU_TELEFONE_FIXO VARCHAR(11),
    NO_EMAIL VARCHAR(100)   
);
